### PR TITLE
adds new badges

### PR DESCRIPTION
**Pull request by ryan-hamblin**
## Details
- The Code Climate job has been updated and now includes your badges. 
- This addition adds the badges to your project's readme.

### Type of Fix
- [ x ] Enhancement :) 

### Testing
- I've tested this locally and it worked in my GH Preview. 
- We still need to add the config and set up for the Code Coverage reporter to run the way it needs to.

### CODE REVIEW

**Comment by ryan-hamblin** [comment]
The final test makes it seem like the Github Actions are running their proper jobs w/ the CI build, generating a Test Coverage file and dumping it back out to code climate. 

It should take a bit for you to see a score generated on the badge as we need to ensure the Labby program runs.

**Review by bamfranceschi — DISMISSED** [review]
Thanks for setting this up, Ryan! I actually realized we need this PR to go to our Development branch instead of master, because otherwise Connect Our Kids will end up with Code Climate the next time we push our changes to their repo.

**Review by bamfranceschi — CHANGES_REQUESTED** [review]
Can you do another PR but to our Development branch instead?

**Comment by ryan-hamblin** [comment]
Awesome. I'll fix.

**Pull request closed without merging**
